2021-10-20 04:51:02,884 INFO    MainThread:584 [wandb_setup.py:_flush():71] setting env: {}
2021-10-20 04:51:02,884 INFO    MainThread:584 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-20 04:51:02,884 INFO    MainThread:584 [wandb_init.py:_log_setup():357] Logging user logs to C:\Users\vikram\mlops_vikram\wandb logging\wandb\run-20211020_045102-1a3merzo\logs\debug.log
2021-10-20 04:51:02,884 INFO    MainThread:584 [wandb_init.py:_log_setup():358] Logging internal logs to C:\Users\vikram\mlops_vikram\wandb logging\wandb\run-20211020_045102-1a3merzo\logs\debug-internal.log
2021-10-20 04:51:02,885 INFO    MainThread:584 [wandb_init.py:init():390] calling init triggers
2021-10-20 04:51:02,885 INFO    MainThread:584 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-20 04:51:02,886 INFO    MainThread:584 [wandb_init.py:init():435] starting backend
2021-10-20 04:51:02,886 INFO    MainThread:584 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=spawn, using: spawn
2021-10-20 04:51:02,890 INFO    MainThread:584 [backend.py:ensure_launched():198] starting backend process...
2021-10-20 04:51:02,958 INFO    MainThread:584 [backend.py:ensure_launched():203] started backend process with pid: 16020
2021-10-20 04:51:02,958 INFO    MainThread:584 [wandb_init.py:init():444] backend started and connected
2021-10-20 04:51:02,960 INFO    MainThread:584 [wandb_init.py:init():503] updated telemetry
2021-10-20 04:51:02,962 INFO    MainThread:584 [wandb_init.py:init():533] communicating current version
2021-10-20 04:51:03,968 INFO    MainThread:584 [wandb_init.py:init():538] got version response 
2021-10-20 04:51:03,968 INFO    MainThread:584 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-10-20 04:51:33,978 INFO    MainThread:584 [interface.py:_communicate_run():903] couldn't get run from backend
2021-10-20 04:51:33,978 ERROR   MainThread:584 [wandb_init.py:init():553] backend process timed out
2021-10-20 04:51:33,978 ERROR   MainThread:584 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-10-20 04:52:09,631 ERROR   MainThread:584 [wandb_init.py:init():897] error
Traceback (most recent call last):
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\wandb_init.py", line 870, in init
    run = wi.init()
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\wandb_init.py", line 566, in init
    backend.cleanup()
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\backend\backend.py", line 227, in cleanup
    self.interface.join()
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 1048, in join
    super(BackendSender, self).join()
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 596, in join
    self._communicate_shutdown()
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 1045, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 799, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\vikram\anaconda3\envs\project-setup\lib\site-packages\wandb\sdk\interface\interface.py", line 804, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
